scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: '192.9.206.60'

  - job_name: 'mysql'
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['mysqld-exporter:9104']
      labels:
        instance: '192.9.206.60'

