global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 10s
scrape_configs:
- job_name: node
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - node-exporter:9100
    labels:
      instance: 192.9.206.60
- job_name: mysql
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - mysqld-exporter:9104
    labels:
      instance: 192.9.206.60
