version: "3.9"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    environment:
      TZ: "Europe/Moscow"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
    restart: unless-stopped
    networks:
      - default_metrics
      
  node-exporter:
    image: prom/node-exporter
    container_name: exporter
    hostname: exporter
    environment:
      TZ: "Europe/Moscow"
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
#      - --collector.systemd
#      - --collector.systemd.private
#      - --collector.systemd.unit-include
#      - (.*).service
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
#      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    restart: unless-stopped
    networks:
      - default_metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - default_metrics

networks:
  default_metrics:
    external: true

